//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "node")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: u64,
    #[sea_orm(column_type = "Double")]
    pub lat: f64,
    #[sea_orm(column_type = "Double")]
    pub lon: f64,
    pub city: Option<String>,
    pub country: Option<String>,
    pub postcode: String,
    pub street: Option<String>,
    pub house_number: Option<String>,
    pub source: Option<String>,
    pub source_date: Option<Date>,
    pub updated_at: DateTime,
    pub version: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

/*
<node id="26516190" version="9" timestamp="2021-03-09T22:45:40Z" lat="52.1955031" lon="5.9624217">
	<tag k="addr:city" v="Apeldoorn"/>
	<tag k="addr:country" v="NL"/>
	<tag k="addr:housenumber" v="221"/>
	<tag k="addr:postcode" v="7331JC"/>
	<tag k="addr:street" v="Arnhemseweg"/>
	<tag k="source" v="BAG"/>
	<tag k="source:date" v="2014-02-11"/>
</node>
 */